---
title: "R Notebook"
output: html_notebook
---

```{r}
3 + 5
6 + 10 

5 - 1
5 * 2
(5 -2) /2
2 ^ 5
28 %% 6
```
```{r}
x <- 10
y <- 15
total = x + y
total
```
```{r}
my_caracter <- "universe"
my_logical <- FALSE
my_caracter
my_logical
```
```{r}
class(my_caracter)
class(my_logical)
```
```{r}
numeric_vector <- c(1,10,49)
caracter_vector <- c("Luis","Antonio","Gutierrez")
boolean_vector <- c(TRUE, FALSE, TRUE)

caracter_vector
boolean_vector
```
Nombrando un Vector
```{r}
poker_vector <- c(140,-50,20,-120,240)
roulette_vector <- c(-24,-50,100,-350,10)

names(poker_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
poker_vector

names(roulette_vector) <- c("Monday","Tuesday","Wednesday","Thursday","Friday")
roulette_vector

total_daily <- poker_vector + roulette_vector
total_daily

total_poker <- sum(poker_vector)
total_poker

sum_total <- sum(poker_vector, roulette_vector)
sum_total

poker_vector
poker_vector[3]
poker_vector[c(1,2,3)]

roulette_vector[2:5]


```
Comparando vectores
```{r}
total_daily <- poker_vector + roulette_vector
total_daily

total_poker <- sum(poker_vector)
total_poker
```

Matrices
```{r}
matrix(1:9,byrow=TRUE,nrow=3)
```
```{r}
new_hope <- c(460.998,314.4)
empire_strike <- c(2980.475,247.900)
return_jedi <- c(309.306,165.8)

box_office <- c(new_hope, empire_strike, return_jedi)

starts_wars_matrix <- matrix(box_office, byrow=TRUE, nrow=3)
starts_wars_matrix
```
```{r}
region <- c("US","non-US")

titles <- c("A new hope","The empire Strikes Back","Return of the Jedi")
colnames(starts_wars_matrix) <- region
rownames(starts_wars_matrix) <- titles

starts_wars_matrix
```
RowSum()
```{r}
worldwide_vector <- rowSums(starts_wars_matrix)
worldwide_vector

all_wars_variable <- cbind(starts_wars_matrix, worldwide_vector)
all_wars_variable

world_cols <- colSums(all_wars_variable)
world_cols

all_wars_variable <- rbind(starts_wars_matrix,world_cols)
all_wars_variable
```
Selection of matrix elements
```{r}
non_us_all <- all_wars_variable[,2]
non_us_all

non_us_all <- all_wars_variable["A new hope",2]
non_us_all

non_us_all <- all_wars_variable[1:3,2]
non_us_all

mean(non_us_all)

```
Arithmetic with matrices
```{r}
us_all <- all_wars_variable[1:3,1]
us_all <- us_all * 0.12
us_all

```
Factors
```{r}
sex_vector <- c("Male","Female","Female","Male","Male")
factor_sex_vector <- factor(sex_vector)
factor_sex_vector

temperature_vector <- c("High","Low","High","Low","Medium")
factor_temperature_vector <- factor(temperature_vector, order=TRUE, levels=c("Low","Medium","High"))
factor_temperature_vector
```
```{r}

survey_vector <- c("M","F","F","M","M")
factor_survey_vector <- factor(survey_vector)

factor_survey_vector

levels(factor_survey_vector) <- c("Female","Male")
factor_survey_vector
```

